### ISSUE TITLE
Selectively enable instead of selectively disable

### ISSUE THREAD

**Issue by daveriedstra** [jdelkins/vim-correction#1]
Thanks for publishing this plugin! This is a feature request that includes a workaround which I'm posting here for others to find.

I don't use packer.nvim and this plugin currently only includes a disable method, not a enable method. It would be nice to have a selective enable method for use in an autocmd in my vimrc.

My current workaround is to use a function which only disables the plugin if the loaded file isn't in the list (selectively disables it):
```vim
" only load autocorrect for markdown and text files
fun! EnableAutocorrect()
    " Don't disable on these file types
    if &ft =~ 'text\|markdown\|gitcommit'
        return
    endif
    let g:loaded_autocorrect = 1
endfun
autocmd BufWritePre * call EnableAutocorrect()
```

(based on [this](https://stackoverflow.com/a/6496995) SO answer.)

**Comment by jdelkins** [comment]
Hi! Thanks for the suggestion, good idea! I implemented it with the latest commit. Details are in the README. Please let me know if this addresses your use case.

**Comment by daveriedstra** [comment]
Fantastic, that's so much better than my solution. Thanks a bunch!
